// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"smart-wardrobe-be/config"
	"smart-wardrobe-be/internal/api/middleware"
	"smart-wardrobe-be/internal/api/routes"
	"smart-wardrobe-be/internal/api/routes/auth"
	category2 "smart-wardrobe-be/internal/api/routes/category"
	"smart-wardrobe-be/internal/api/routes/community"
	"smart-wardrobe-be/internal/api/routes/me"
	outfit2 "smart-wardrobe-be/internal/api/routes/outfit"
	"smart-wardrobe-be/internal/api/routes/subscription"
	wardrobe2 "smart-wardrobe-be/internal/api/routes/wardrobe"
	"smart-wardrobe-be/internal/bootstrap"
	usecase3 "smart-wardrobe-be/internal/modules/community/application/usecase"
	persistence4 "smart-wardrobe-be/internal/modules/community/infrastructure/persistence"
	handler4 "smart-wardrobe-be/internal/modules/community/presentation/handler"
	"smart-wardrobe-be/internal/modules/identity/application/usecase"
	caching2 "smart-wardrobe-be/internal/modules/identity/infrastructure/caching"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/communication"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/persistence"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/security"
	"smart-wardrobe-be/internal/modules/identity/presentation/handler"
	usecase2 "smart-wardrobe-be/internal/modules/subscription/application/usecase"
	"smart-wardrobe-be/internal/modules/subscription/infrastructure/payment/payos"
	persistence2 "smart-wardrobe-be/internal/modules/subscription/infrastructure/persistence"
	handler2 "smart-wardrobe-be/internal/modules/subscription/presentation/handler"
	"smart-wardrobe-be/internal/modules/subscription/presentation/worker"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/category"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/outfit"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/wardrobe"
	messaging2 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/messaging"
	persistence3 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/persistence"
	search2 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/search"
	handler3 "smart-wardrobe-be/internal/modules/wardrobe/presentation/handler"
	worker2 "smart-wardrobe-be/internal/modules/wardrobe/presentation/worker"
	"smart-wardrobe-be/internal/shared/infrastructure/ai"
	"smart-wardrobe-be/internal/shared/infrastructure/caching"
	"smart-wardrobe-be/internal/shared/infrastructure/db"
	"smart-wardrobe-be/internal/shared/infrastructure/media"
	"smart-wardrobe-be/internal/shared/infrastructure/messaging"
	"smart-wardrobe-be/internal/shared/infrastructure/search"
	"smart-wardrobe-be/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, l logger.Interface) (*bootstrap.App, func(), error) {
	gormDB, err := db.NewPostgresConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iUserRepository := persistence.NewUserRepository(gormDB)
	client, err := caching.NewRedisConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iOtpService := caching2.NewRedisOtpService(client, cfg)
	iEmailService := communication.NewGmailSmtpService(cfg)
	iPasswordHasher := security.NewBcryptPasswordHasher()
	iRegisterUseCase := usecase.NewRegisterUseCase(iUserRepository, iOtpService, iEmailService, iPasswordHasher, cfg)
	iRefreshTokenRepository := persistence.NewRefreshTokenRepository(gormDB)
	iTokenBlacklistService := security.NewRedisTokenBlacklistService(client)
	iUnitOfWork := db.NewGormUnitOfWork(gormDB)
	iSessionUseCase := usecase.NewSessionUseCase(iUserRepository, iRefreshTokenRepository, iPasswordHasher, iTokenBlacklistService, cfg, iUnitOfWork)
	iPasswordRecoveryUseCase := usecase.NewPasswordRecoveryUseCase(iUserRepository, iRefreshTokenRepository, iOtpService, iEmailService, iPasswordHasher, cfg, iUnitOfWork)
	authHandler := handler.NewAuthHandler(iRegisterUseCase, iSessionUseCase, iPasswordRecoveryUseCase, cfg)
	authMiddleware := middleware.NewAuthMiddleware(cfg, iTokenBlacklistService, iUserRepository)
	authRouter := auth.NewRouter(authHandler, authMiddleware)
	iUserSubscriptionRepository := persistence2.NewUserSubscriptionRepository(gormDB)
	iSubscriptionPlanRepository := persistence2.NewSubscriptionPlanRepository(gormDB)
	iUserWalletRepository := persistence2.NewUserWalletRepository(gormDB)
	iWalletStatementRepository := persistence2.NewWalletStatementRepository(gormDB)
	iUserDailyQuotaRepository := persistence2.NewUserDailyQuotaRepository(gormDB)
	iSubscriptionPlanUseCase := usecase2.NewSubscriptionPlanUseCase(iSubscriptionPlanRepository)
	iUserQuotaUseCase := usecase2.NewUserQuotaUseCase(iUserDailyQuotaRepository, iUserSubscriptionRepository, iSubscriptionPlanRepository)
	iSubscriptionUseCase := usecase2.NewSubscriptionUseCase(iUnitOfWork, iUserSubscriptionRepository, iSubscriptionPlanRepository, iUserWalletRepository, iWalletStatementRepository, iUserDailyQuotaRepository, cfg, l, iSubscriptionPlanUseCase, iUserQuotaUseCase)
	iMediaService := media.NewCloudinaryService(cfg)
	iUserUseCase := usecase.NewUserUseCase(iUserRepository, iPasswordHasher, iRefreshTokenRepository, iSubscriptionUseCase, iMediaService, cfg)
	meHandler := handler.NewMeHandler(iUserUseCase)
	meRouter := me.NewRouter(meHandler, authMiddleware)
	subscriptionHandler := handler2.NewSubscriptionHandler(iSubscriptionUseCase)
	iDepositTransactionRepository := persistence2.NewDepositTransactionRepository(gormDB)
	iPaymentGatewayService := payos.NewPayOSService(cfg)
	iWalletUseCase := usecase2.NewWalletUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iSubscriptionPurchaseUseCase := usecase2.NewSubscriptionPurchaseUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iPaymentWebhookUseCase := usecase2.NewPaymentWebhookUseCase(cfg, iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork)
	billingHandler := handler2.NewBillingHandler(l, iWalletUseCase, iSubscriptionPurchaseUseCase, iPaymentWebhookUseCase)
	subscriptionRouter := subscription.NewRouter(subscriptionHandler, billingHandler, authMiddleware)
	iWardrobeItemRepository := persistence3.NewWardrobeItemRepository(gormDB)
	iCategoryRepository := persistence3.NewCategoryRepository(gormDB)
	iConversationalContextRepository := persistence3.NewConversationalContextRepository(gormDB)
	iMessageRepository := persistence3.NewMessageRepository(gormDB)
	elasticsearchClient := search.NewElasticsearchClient(cfg, l)
	iWardrobeSearchService := search2.NewWardrobeSearchService(elasticsearchClient)
	iaiService := ai.NewAIService(cfg, l)
	rabbitMQClient, err := messaging.NewRabbitMQClient(cfg, l)
	if err != nil {
		return nil, nil, err
	}
	iWardrobeUseCase := wardrobe.NewWardrobeUseCase(cfg, l, iWardrobeItemRepository, iCategoryRepository, iConversationalContextRepository, iMessageRepository, iWardrobeSearchService, iMediaService, iaiService, iSubscriptionUseCase, iUserQuotaUseCase, rabbitMQClient, iUnitOfWork)
	wardrobeHandler := handler3.NewWardrobeHandler(iWardrobeUseCase)
	wardrobeRouter := wardrobe2.NewRouter(wardrobeHandler, authMiddleware)
	iOutfitRepository := persistence3.NewOutfitRepository(gormDB)
	iOutfitUseCase := outfit.NewOutfitUseCase(cfg, l, iOutfitRepository, iWardrobeItemRepository, iSubscriptionUseCase, iMediaService)
	outfitHandler := handler3.NewOutfitHandler(iOutfitUseCase)
	outfitRouter := outfit2.NewRouter(outfitHandler, authMiddleware)
	iCategoryUseCase := category.NewCategoryUseCase(l, iCategoryRepository)
	categoryHandler := handler3.NewCategoryHandler(iCategoryUseCase)
	categoryRouter := category2.NewRouter(categoryHandler)
	iPostRepository := persistence4.NewPostRepository(gormDB)
	iPostItemRepository := persistence4.NewPostItemRepository(gormDB)
	iPostMediaRepository := persistence4.NewPostMediaRepository(gormDB)
	iCommentRepository := persistence4.NewCommentRepository(gormDB)
	iPostUseCase := usecase3.NewPostUseCase(iPostRepository, iPostItemRepository, iPostMediaRepository, iCommentRepository, iWardrobeUseCase, iUnitOfWork)
	postHandler := handler4.NewPostHandler(iPostUseCase)
	iLikeRepository := persistence4.NewLikeRepository(gormDB)
	iPostInteractionUseCase := usecase3.NewPostInteractionUseCase(iPostRepository, iCommentRepository, iLikeRepository, iUnitOfWork)
	postInteractionHandler := handler4.NewPostInteractionHandler(iPostInteractionUseCase)
	iItemTransferUseCase := usecase3.NewItemTransferUseCase(iPostRepository, iPostItemRepository, iUserUseCase, iWardrobeUseCase, iUnitOfWork)
	itemTransferHandler := handler4.NewItemTransferHandler(iItemTransferUseCase)
	communityRouter := community.NewRouter(postHandler, postInteractionHandler, itemTransferHandler, authMiddleware)
	appRouter := &routes.AppRouter{
		AuthRouter:         authRouter,
		MeRouter:           meRouter,
		SubscriptionRouter: subscriptionRouter,
		WardrobeRouter:     wardrobeRouter,
		OutfitRouter:       outfitRouter,
		CategoryRouter:     categoryRouter,
		CommunityRouter:    communityRouter,
	}
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(cfg)
	engine := routes.NewEngine(cfg, appRouter, l, rateLimitMiddleware)
	iSubscriptionRenewalWorker := worker.NewSubscriptionRenewalWorker(iSubscriptionUseCase, l)
	iWardrobeBatchUploadJobConsumer := messaging2.NewWardrobeBatchUploadJobConsumer(rabbitMQClient, l)
	wardrobeBatchUploadWorker := worker2.NewWardrobeBatchUploadWorker(iWardrobeBatchUploadJobConsumer, iWardrobeUseCase, l)
	iSearchSyncEventConsumer := messaging2.NewSearchSyncEventConsumer(rabbitMQClient, l)
	iWardrobeSearchIndexService := search2.NewWardrobeSearchIndexService(elasticsearchClient)
	searchSyncWorker := worker2.NewSearchSyncWorker(iSearchSyncEventConsumer, iWardrobeSearchIndexService, iWardrobeItemRepository, l)
	iFailedItemsCleanupWorker := worker2.NewFailedItemsCleanupWorker(iWardrobeUseCase, l)
	appWorkers := &bootstrap.AppWorkers{
		RenewalWorker:             iSubscriptionRenewalWorker,
		WardrobeBatchUploadWorker: wardrobeBatchUploadWorker,
		ESAsyncWorker:             searchSyncWorker,
		FailedItemsCleanupWorker:  iFailedItemsCleanupWorker,
	}
	app := bootstrap.NewApp(cfg, engine, appWorkers)
	return app, func() {
	}, nil
}
