// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"smart-wardrobe-be/config"
	"smart-wardrobe-be/internal/api/middleware"
	"smart-wardrobe-be/internal/api/routes"
	"smart-wardrobe-be/internal/api/routes/admin"
	"smart-wardrobe-be/internal/api/routes/auth"
	category2 "smart-wardrobe-be/internal/api/routes/category"
	"smart-wardrobe-be/internal/api/routes/community"
	"smart-wardrobe-be/internal/api/routes/me"
	outfit2 "smart-wardrobe-be/internal/api/routes/outfit"
	subscription2 "smart-wardrobe-be/internal/api/routes/subscription"
	wardrobe2 "smart-wardrobe-be/internal/api/routes/wardrobe"
	"smart-wardrobe-be/internal/bootstrap"
	"smart-wardrobe-be/internal/modules/community/application/usecase/admin_moderation"
	"smart-wardrobe-be/internal/modules/community/application/usecase/item_transfer"
	"smart-wardrobe-be/internal/modules/community/application/usecase/post"
	"smart-wardrobe-be/internal/modules/community/application/usecase/post_interaction"
	persistence3 "smart-wardrobe-be/internal/modules/community/infrastructure/persistence"
	handler2 "smart-wardrobe-be/internal/modules/community/presentation/handler"
	worker2 "smart-wardrobe-be/internal/modules/community/presentation/worker"
	"smart-wardrobe-be/internal/modules/identity/application/usecase"
	caching2 "smart-wardrobe-be/internal/modules/identity/infrastructure/caching"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/communication"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/persistence"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/security"
	"smart-wardrobe-be/internal/modules/identity/presentation/handler"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/plan"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/purchase"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/quota"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/subscription"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/wallet"
	"smart-wardrobe-be/internal/modules/subscription/application/usecase/webhook"
	"smart-wardrobe-be/internal/modules/subscription/infrastructure/payment/payos"
	persistence2 "smart-wardrobe-be/internal/modules/subscription/infrastructure/persistence"
	handler4 "smart-wardrobe-be/internal/modules/subscription/presentation/handler"
	"smart-wardrobe-be/internal/modules/subscription/presentation/worker"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/category"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/outfit"
	"smart-wardrobe-be/internal/modules/wardrobe/application/usecase/wardrobe"
	messaging2 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/messaging"
	persistence4 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/persistence"
	search2 "smart-wardrobe-be/internal/modules/wardrobe/infrastructure/search"
	handler3 "smart-wardrobe-be/internal/modules/wardrobe/presentation/handler"
	worker3 "smart-wardrobe-be/internal/modules/wardrobe/presentation/worker"
	"smart-wardrobe-be/internal/shared/infrastructure/ai"
	"smart-wardrobe-be/internal/shared/infrastructure/caching"
	"smart-wardrobe-be/internal/shared/infrastructure/db"
	"smart-wardrobe-be/internal/shared/infrastructure/media"
	"smart-wardrobe-be/internal/shared/infrastructure/messaging"
	"smart-wardrobe-be/internal/shared/infrastructure/search"
	"smart-wardrobe-be/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, l logger.Interface) (*bootstrap.App, func(), error) {
	gormDB, err := db.NewPostgresConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iUserRepository := persistence.NewUserRepository(gormDB)
	iPasswordHasher := security.NewBcryptPasswordHasher()
	iRefreshTokenRepository := persistence.NewRefreshTokenRepository(gormDB)
	client, err := caching.NewRedisConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iTokenBlacklistService := security.NewRedisTokenBlacklistService(client)
	iUnitOfWork := db.NewGormUnitOfWork(gormDB)
	iUserSubscriptionRepository := persistence2.NewUserSubscriptionRepository(gormDB)
	iSubscriptionPlanRepository := persistence2.NewSubscriptionPlanRepository(gormDB)
	iUserWalletRepository := persistence2.NewUserWalletRepository(gormDB)
	iWalletStatementRepository := persistence2.NewWalletStatementRepository(gormDB)
	iUserDailyQuotaRepository := persistence2.NewUserDailyQuotaRepository(gormDB)
	iSubscriptionPlanUseCase := plan.NewSubscriptionPlanUseCase(iSubscriptionPlanRepository)
	iUserQuotaUseCase := quota.NewUserQuotaUseCase(iUserDailyQuotaRepository, iUserSubscriptionRepository, iSubscriptionPlanRepository)
	iSubscriptionUseCase := subscription.NewSubscriptionUseCase(iUnitOfWork, iUserSubscriptionRepository, iSubscriptionPlanRepository, iUserWalletRepository, iWalletStatementRepository, iUserDailyQuotaRepository, cfg, l, iSubscriptionPlanUseCase, iUserQuotaUseCase)
	iMediaService := media.NewCloudinaryService(cfg)
	iUserUseCase := usecase.NewUserUseCase(iUserRepository, iPasswordHasher, iRefreshTokenRepository, iTokenBlacklistService, iSubscriptionUseCase, iMediaService, cfg)
	adminHandler := handler.NewAdminHandler(iUserUseCase)
	iPostRepository := persistence3.NewPostRepository(gormDB)
	iPostItemRepository := persistence3.NewPostItemRepository(gormDB)
	iPostMediaRepository := persistence3.NewPostMediaRepository(gormDB)
	iCommentRepository := persistence3.NewCommentRepository(gormDB)
	iWardrobeItemRepository := persistence4.NewWardrobeItemRepository(gormDB)
	iCategoryRepository := persistence4.NewCategoryRepository(gormDB)
	iConversationalContextRepository := persistence4.NewConversationalContextRepository(gormDB)
	iMessageRepository := persistence4.NewMessageRepository(gormDB)
	elasticsearchClient := search.NewElasticsearchClient(cfg, l)
	iWardrobeSearchService := search2.NewWardrobeSearchService(elasticsearchClient)
	iaiService := ai.NewAIService(cfg, l)
	rabbitMQClient, err := messaging.NewRabbitMQClient(cfg, l)
	if err != nil {
		return nil, nil, err
	}
	iWardrobeUseCase := wardrobe.NewWardrobeUseCase(cfg, l, iWardrobeItemRepository, iCategoryRepository, iConversationalContextRepository, iMessageRepository, iWardrobeSearchService, iMediaService, iaiService, iSubscriptionUseCase, iUserQuotaUseCase, rabbitMQClient, iUnitOfWork)
	iAdminCommunityModerationUseCase := admin_moderation.NewAdminCommunityModerationUseCase(l, iPostRepository, iPostItemRepository, iPostMediaRepository, iCommentRepository, iWardrobeUseCase, iUnitOfWork)
	handlerAdminHandler := handler2.NewAdminHandler(iAdminCommunityModerationUseCase)
	wardrobeItemHandler := handler3.NewWardrobeItemHandler(iWardrobeUseCase, iWardrobeUseCase, iWardrobeUseCase)
	authMiddleware := middleware.NewAuthMiddleware(cfg, iTokenBlacklistService)
	adminRouter := admin.NewRouter(adminHandler, handlerAdminHandler, wardrobeItemHandler, authMiddleware)
	iOtpService := caching2.NewRedisOtpService(client, cfg)
	iEmailService := communication.NewGmailSmtpService(cfg)
	iRegisterUseCase := usecase.NewRegisterUseCase(iUserRepository, iOtpService, iEmailService, iPasswordHasher, cfg)
	iSessionUseCase := usecase.NewSessionUseCase(iUserRepository, iRefreshTokenRepository, iPasswordHasher, iTokenBlacklistService, cfg, iUnitOfWork)
	iPasswordRecoveryUseCase := usecase.NewPasswordRecoveryUseCase(iUserRepository, iRefreshTokenRepository, iOtpService, iEmailService, iPasswordHasher, iTokenBlacklistService, cfg, iUnitOfWork)
	authHandler := handler.NewAuthHandler(iRegisterUseCase, iSessionUseCase, iPasswordRecoveryUseCase, cfg)
	authRouter := auth.NewRouter(authHandler, authMiddleware)
	meHandler := handler.NewMeHandler(iUserUseCase)
	meRouter := me.NewRouter(meHandler, authMiddleware)
	subscriptionHandler := handler4.NewSubscriptionHandler(iSubscriptionUseCase)
	iDepositTransactionRepository := persistence2.NewDepositTransactionRepository(gormDB)
	iPaymentGatewayService := payos.NewPayOSService(cfg)
	iWalletUseCase := wallet.NewWalletUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iSubscriptionPurchaseUseCase := purchase.NewSubscriptionPurchaseUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iPaymentWebhookUseCase := webhook.NewPaymentWebhookUseCase(cfg, iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork, l)
	billingHandler := handler4.NewBillingHandler(l, iWalletUseCase, iSubscriptionPurchaseUseCase, iPaymentWebhookUseCase)
	subscriptionRouter := subscription2.NewRouter(subscriptionHandler, billingHandler, authMiddleware)
	wardrobeAIHandler := handler3.NewWardrobeAIHandler(iWardrobeUseCase)
	wardrobeRouter := wardrobe2.NewRouter(wardrobeItemHandler, wardrobeAIHandler, authMiddleware)
	iOutfitRepository := persistence4.NewOutfitRepository(gormDB)
	iOutfitUseCase := outfit.NewOutfitUseCase(cfg, l, iOutfitRepository, iWardrobeItemRepository, iSubscriptionUseCase, iMediaService)
	outfitHandler := handler3.NewOutfitHandler(iOutfitUseCase)
	outfitRouter := outfit2.NewRouter(outfitHandler, authMiddleware)
	iCategoryUseCase := category.NewCategoryUseCase(l, iCategoryRepository)
	categoryHandler := handler3.NewCategoryHandler(iCategoryUseCase)
	categoryRouter := category2.NewRouter(categoryHandler)
	iPostScoreRepository := persistence3.NewPostScoreRepository(gormDB)
	iLikeRepository := persistence3.NewLikeRepository(gormDB)
	iUserPostUseCase := post.NewUserPostUseCase(cfg, l, iPostRepository, iPostScoreRepository, iPostItemRepository, iPostMediaRepository, iCommentRepository, iLikeRepository, iUserUseCase, iWardrobeUseCase, iMediaService, iUnitOfWork)
	postHandler := handler2.NewPostHandler(iUserPostUseCase)
	iUserPostInteractionUseCase := post_interaction.NewPostInteractionUseCase(iPostRepository, iCommentRepository, iLikeRepository, iUnitOfWork)
	postInteractionHandler := handler2.NewPostInteractionHandler(iUserPostInteractionUseCase)
	iTransferRequestRepository := persistence3.NewTransferRequestRepository(gormDB)
	iItemTransferUseCase := item_transfer.NewItemTransferUseCase(iPostRepository, iPostItemRepository, iTransferRequestRepository, iUserUseCase, iWardrobeUseCase, iUnitOfWork)
	itemTransferHandler := handler2.NewItemTransferHandler(iItemTransferUseCase)
	communityRouter := community.NewRouter(postHandler, postInteractionHandler, itemTransferHandler, authMiddleware)
	appRouter := &routes.AppRouter{
		AdminRouter:        adminRouter,
		AuthRouter:         authRouter,
		MeRouter:           meRouter,
		SubscriptionRouter: subscriptionRouter,
		WardrobeRouter:     wardrobeRouter,
		OutfitRouter:       outfitRouter,
		CategoryRouter:     categoryRouter,
		CommunityRouter:    communityRouter,
	}
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(cfg)
	engine := routes.NewEngine(cfg, appRouter, l, rateLimitMiddleware)
	iSubscriptionRenewalWorker := worker.NewSubscriptionRenewalWorker(iSubscriptionUseCase, l)
	iPostHotnessWorker := worker2.NewPostHotnessWorker(iPostRepository, iPostScoreRepository, l)
	iWardrobeBatchUploadJobConsumer := messaging2.NewWardrobeBatchUploadJobConsumer(rabbitMQClient, l)
	wardrobeBatchUploadWorker := worker3.NewWardrobeBatchUploadWorker(iWardrobeBatchUploadJobConsumer, iWardrobeUseCase, l)
	iSearchSyncEventConsumer := messaging2.NewSearchSyncEventConsumer(rabbitMQClient, l)
	iWardrobeSearchIndexService := search2.NewWardrobeSearchIndexService(elasticsearchClient)
	searchSyncWorker := worker3.NewSearchSyncWorker(iSearchSyncEventConsumer, iWardrobeSearchIndexService, iWardrobeItemRepository, l)
	iFailedItemsCleanupWorker := worker3.NewFailedItemsCleanupWorker(iWardrobeUseCase, l)
	appWorkers := &bootstrap.AppWorkers{
		RenewalWorker:             iSubscriptionRenewalWorker,
		PostHotnessWorker:         iPostHotnessWorker,
		WardrobeBatchUploadWorker: wardrobeBatchUploadWorker,
		ESAsyncWorker:             searchSyncWorker,
		FailedItemsCleanupWorker:  iFailedItemsCleanupWorker,
	}
	app := bootstrap.NewApp(cfg, engine, appWorkers)
	return app, func() {
	}, nil
}
