// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"smart-wardrobe-be/config"
	"smart-wardrobe-be/internal/api/middleware"
	"smart-wardrobe-be/internal/api/routes"
	"smart-wardrobe-be/internal/api/routes/auth"
	"smart-wardrobe-be/internal/api/routes/me"
	"smart-wardrobe-be/internal/api/routes/subscription"
	"smart-wardrobe-be/internal/bootstrap"
	"smart-wardrobe-be/internal/modules/identity/application/usecase"
	caching2 "smart-wardrobe-be/internal/modules/identity/infrastructure/caching"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/communication"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/persistence"
	"smart-wardrobe-be/internal/modules/identity/infrastructure/security"
	"smart-wardrobe-be/internal/modules/identity/presentation/handler"
	"smart-wardrobe-be/internal/modules/subscription/application/contract"
	usecase2 "smart-wardrobe-be/internal/modules/subscription/application/usecase"
	"smart-wardrobe-be/internal/modules/subscription/infrastructure/payment/payos"
	persistence2 "smart-wardrobe-be/internal/modules/subscription/infrastructure/persistence"
	handler2 "smart-wardrobe-be/internal/modules/subscription/presentation/handler"
	"smart-wardrobe-be/internal/modules/subscription/presentation/worker"
	"smart-wardrobe-be/internal/shared/infrastructure/caching"
	"smart-wardrobe-be/internal/shared/infrastructure/db"
	"smart-wardrobe-be/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, l logger.Interface) (*bootstrap.App, func(), error) {
	gormDB, err := db.NewPostgresConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iUserRepository := persistence.NewUserRepository(gormDB)
	iRefreshTokenRepository := persistence.NewRefreshTokenRepository(gormDB)
	client, err := caching.NewRedisConnection(cfg)
	if err != nil {
		return nil, nil, err
	}
	iOtpService := caching2.NewRedisOtpService(client, cfg)
	iEmailService := communication.NewGmailSmtpService(cfg)
	iPasswordHasher := security.NewBcryptPasswordHasher()
	iTokenBlacklistService := security.NewRedisTokenBlacklistService(client)
	iSubscriptionPlanRepository := persistence2.NewSubscriptionPlanRepository(gormDB)
	iUserSubscriptionRepository := persistence2.NewUserSubscriptionRepository(gormDB)
	iUserDailyQuotaRepository := persistence2.NewUserDailyQuotaRepository(gormDB)
	iSubscriptionModuleContract := contract.NewSubscriptionModuleContractImpl(iSubscriptionPlanRepository, iUserSubscriptionRepository, iUserDailyQuotaRepository)
	iUnitOfWork := db.NewGormUnitOfWork(gormDB)
	iAuthUseCase := usecase.NewAuthUseCase(iUserRepository, iRefreshTokenRepository, iOtpService, iEmailService, iPasswordHasher, iTokenBlacklistService, iSubscriptionModuleContract, iUnitOfWork, cfg)
	authHandler := handler.NewAuthHandler(iAuthUseCase, cfg)
	authMiddleware := middleware.NewAuthMiddleware(cfg)
	authRouter := auth.NewRouter(authHandler, authMiddleware)
	iUserUseCase := usecase.NewUserUseCase(iUserRepository, iPasswordHasher, iRefreshTokenRepository, iSubscriptionModuleContract)
	meHandler := handler.NewMeHandler(iUserUseCase)
	meRouter := me.NewRouter(meHandler, authMiddleware)
	iUserWalletRepository := persistence2.NewUserWalletRepository(gormDB)
	iWalletStatementRepository := persistence2.NewWalletStatementRepository(gormDB)
	iSubscriptionUseCase := usecase2.NewSubscriptionUseCase(iUnitOfWork, iSubscriptionModuleContract, iUserSubscriptionRepository, iSubscriptionPlanRepository, iUserWalletRepository, iWalletStatementRepository, iUserDailyQuotaRepository, cfg)
	dailyQuotaHandler := handler2.NewDailyQuotaHandler(iSubscriptionUseCase)
	iDepositTransactionRepository := persistence2.NewDepositTransactionRepository(gormDB)
	iPaymentGatewayService := payos.NewPayOSService(cfg)
	iWalletUseCase := usecase2.NewWalletUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iSubscriptionPurchaseUseCase := usecase2.NewSubscriptionPurchaseUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	iPaymentWebhookUseCase := usecase2.NewPaymentWebhookUseCase(iUserWalletRepository, iDepositTransactionRepository, iWalletStatementRepository, iSubscriptionPlanRepository, iUserSubscriptionRepository, iPaymentGatewayService, iUnitOfWork, cfg)
	billingHandler := handler2.NewBillingHandler(iWalletUseCase, iSubscriptionPurchaseUseCase, iPaymentWebhookUseCase)
	subscriptionRouter := subscription.NewRouter(dailyQuotaHandler, billingHandler, authMiddleware)
	appRouter := &routes.AppRouter{
		AuthRouter:         authRouter,
		MeRouter:           meRouter,
		SubscriptionRouter: subscriptionRouter,
	}
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(cfg)
	engine := routes.NewEngine(cfg, appRouter, l, rateLimitMiddleware)
	iSubscriptionRenewalWorker := worker.NewSubscriptionRenewalWorker(iSubscriptionUseCase, l)
	app := bootstrap.NewApp(cfg, engine, iSubscriptionRenewalWorker)
	return app, func() {
	}, nil
}
