// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/forgot-password": {
            "post": {
                "description": "Gửi mã OTP xác thực khôi phục mật khẩu qua email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Yêu cầu khôi phục mật khẩu",
                "parameters": [
                    {
                        "description": "Email nhận OTP",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.SendForgotPasswordOtpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/forgot-password/confirm-otp": {
            "post": {
                "description": "Xác thực mã OTP khôi phục mật khẩu và lưu token tạm thời vào cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Xác thực OTP khôi phục mật khẩu",
                "parameters": [
                    {
                        "description": "Mã OTP và Email",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmForgotPasswordOtpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Đăng nhập hệ thống bằng username hoặc email và password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "accessToken in data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Đăng xuất người dùng, vô hiệu hóa token hiện tại và xóa cookie refresh token \u0026 access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng xuất",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh-token": {
            "post": {
                "description": "Sử dụng refresh token trong cookie để lấy access token mới và xoay vòng refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Xoay vòng token (Refresh Token)",
                "responses": {
                    "200": {
                        "description": "accessToken in data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Đăng ký tài khoản mới cho người dùng và gửi OTP xác thực qua email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register/confirm-otp": {
            "post": {
                "description": "Xác nhận OTP gửi qua email để kích hoạt tài khoản",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Xác thực OTP đăng ký",
                "parameters": [
                    {
                        "description": "Mã OTP xác thực",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmRegisterOtpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/reset-password": {
            "post": {
                "description": "Sử dụng token tạm thời từ cookie để tiến hành đặt mật khẩu mới",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đặt lại mật khẩu",
                "parameters": [
                    {
                        "description": "Mật khẩu mới và mật khẩu xác nhận",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "description": "Lấy thông tin chi tiết tài khoản của người dùng hiện tại đang đăng nhập",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Lấy thông tin cá nhân",
                "responses": {
                    "200": {
                        "description": "Thông tin người dùng",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Cập nhật các trường thông tin của người dùng hiện tại đang đăng nhập",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Cập nhật thông tin cá nhân",
                "parameters": [
                    {
                        "description": "Thông tin cập nhật",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UpdateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thông tin người dùng sau khi cập nhật",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/me/change-password": {
            "put": {
                "description": "Thay đổi mật khẩu cho người dùng hiện tại đang đăng nhập",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Đổi mật khẩu",
                "parameters": [
                    {
                        "description": "Mật khẩu cũ và mới",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ChangePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/daily-quota": {
            "get": {
                "description": "Lấy hạn ngạch chi tiết và trạng thái sử dụng của người dùng trong ngày",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Lấy hạn ngạch sử dụng hàng ngày",
                "responses": {
                    "200": {
                        "description": "Hạn ngạch sử dụng",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/purchase": {
            "post": {
                "description": "Khởi tạo link thanh toán VietQR qua cổng PayOS để đăng ký gói cước trực tiếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Đăng ký mua gói cước trực tiếp",
                "parameters": [
                    {
                        "description": "Thông tin gói cước",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.DirectPurchaseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Link thanh toán",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/purchase-with-wallet": {
            "post": {
                "description": "Thực hiện mua gói cước bằng cách trừ số dư ví nội bộ của người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Đăng ký mua gói cước bằng ví nội bộ",
                "parameters": [
                    {
                        "description": "Thông tin gói cước (chỉ cần planSlug)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.DirectPurchaseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kết quả đăng ký",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/toggle-auto-renew": {
            "patch": {
                "description": "Thiết lập bật hoặc tắt tính năng tự động gia hạn gói cước qua ví nội bộ khi hết hạn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Thiết lập tự động gia hạn gói cước",
                "parameters": [
                    {
                        "description": "Trạng thái thiết lập tự động gia hạn",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_presentation_dto.SetAutoRenewReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trạng thái tự động gia hạn mới",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/wallet": {
            "get": {
                "description": "Lấy số dư hiện có trong ví nội bộ của người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Lấy số dư ví người dùng",
                "responses": {
                    "200": {
                        "description": "Số dư ví",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/wallet/statements": {
            "get": {
                "description": "Lấy nhật ký biến động số dư ví nội bộ của người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Lấy lịch sử giao dịch ví nội bộ",
                "responses": {
                    "200": {
                        "description": "Danh sách lịch sử giao dịch",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/me/wallet/topup": {
            "post": {
                "description": "Khởi tạo link thanh toán VietQR qua cổng PayOS để nạp tiền vào ví",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Tạo yêu cầu nạp tiền vào ví nội bộ",
                "parameters": [
                    {
                        "description": "Thông tin nạp tiền",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.WalletTopUpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Link thanh toán",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/payos-webhook": {
            "post": {
                "description": "Tiếp nhận và xác thực thông báo IPN từ PayOS khi người dùng thanh toán thành công",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Billing"
                ],
                "summary": "Xử lý Webhook thông báo thanh toán từ PayOS",
                "parameters": [
                    {
                        "description": "Webhook Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kết quả xử lý",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/plans": {
            "get": {
                "description": "Lấy danh sách tất cả các gói đăng ký Premium hiện có",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Lấy danh sách các gói Premium",
                "responses": {
                    "200": {
                        "description": "Danh sách gói cước",
                        "schema": {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "smart-wardrobe-be_internal_modules_identity_application_dto.ChangePasswordReq": {
            "type": "object",
            "required": [
                "confirmPassword",
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "logoutAllDevices": {
                    "type": "boolean"
                },
                "newPassword": {
                    "type": "string",
                    "minLength": 6
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmForgotPasswordOtpReq": {
            "type": "object",
            "required": [
                "email",
                "otpCode"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otpCode": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmRegisterOtpReq": {
            "type": "object",
            "required": [
                "email",
                "otpCode"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otpCode": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.LoginReq": {
            "type": "object",
            "required": [
                "loginName",
                "password"
            ],
            "properties": {
                "loginName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.RegisterReq": {
            "type": "object",
            "required": [
                "address",
                "confirmPassword",
                "dateOfBirth",
                "email",
                "firstName",
                "password",
                "username"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "confirmPassword": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "enum": [
                        0,
                        1,
                        2,
                        3
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender"
                        }
                    ]
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.ResetPasswordReq": {
            "type": "object",
            "required": [
                "confirmPassword",
                "newPassword"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "logoutAllDevices": {
                    "type": "boolean"
                },
                "newPassword": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.SendForgotPasswordOtpReq": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.UpdateProfileReq": {
            "type": "object",
            "required": [
                "firstName"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "enum": [
                        0,
                        1,
                        2,
                        3
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender"
                        }
                    ]
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.UserBodyProfileRes": {
            "type": "object",
            "properties": {
                "bodyType": {
                    "type": "string"
                },
                "estimatedBodyShape": {
                    "type": "string"
                },
                "fitPreference": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "recommendedSize": {
                    "type": "string"
                },
                "skinTone": {
                    "type": "string"
                },
                "stylingNotes": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.UserRes": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bodyProfile": {
                    "description": "Quota        *UserQuotaRes       ` + "`" + `json:\"quota,omitempty\"` + "`" + `",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserBodyProfileRes"
                        }
                    ]
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "roleSlug": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "subscription": {
                    "$ref": "#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserSubscriptionRes"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_identity_application_dto.UserSubscriptionRes": {
            "type": "object",
            "properties": {
                "aiChatDailyQuota": {
                    "type": "integer"
                },
                "aiOutfitDailyQuota": {
                    "type": "integer"
                },
                "expiresAt": {
                    "type": "string"
                },
                "maxOutfits": {
                    "type": "integer"
                },
                "maxWardrobeItems": {
                    "type": "integer"
                },
                "planId": {
                    "type": "string"
                },
                "planName": {
                    "type": "string"
                },
                "planSlug": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_subscription_application_dto.DirectPurchaseReq": {
            "type": "object",
            "required": [
                "planSlug"
            ],
            "properties": {
                "cancelUrl": {
                    "type": "string"
                },
                "planSlug": {
                    "type": "string"
                },
                "returnUrl": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookData": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "orderCode": {
                    "type": "integer"
                },
                "paymentLinkId": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "transactionDateTime": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookData"
                },
                "desc": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_subscription_application_dto.WalletTopUpReq": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "cancelUrl": {
                    "type": "string"
                },
                "returnUrl": {
                    "type": "string"
                }
            }
        },
        "smart-wardrobe-be_internal_modules_subscription_presentation_dto.SetAutoRenewReq": {
            "type": "object",
            "required": [
                "enabled"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "smart-wardrobe-be_internal_shared_domain_constants_gender.Gender": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Unknown",
                "Male",
                "Female",
                "Other"
            ]
        },
        "smart-wardrobe-be_internal_shared_presentation.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Smart Wardrobe API Document",
	Description:      "API docs for Smart Wardrobe.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
