definitions:
  smart-wardrobe-be_internal_modules_identity_application_dto.ChangePasswordReq:
    properties:
      confirmPassword:
        type: string
      logoutAllDevices:
        type: boolean
      newPassword:
        minLength: 6
        type: string
      oldPassword:
        type: string
    required:
    - confirmPassword
    - newPassword
    - oldPassword
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmForgotPasswordOtpReq:
    properties:
      email:
        type: string
      otpCode:
        type: string
    required:
    - email
    - otpCode
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmRegisterOtpReq:
    properties:
      email:
        type: string
      otpCode:
        type: string
    required:
    - email
    - otpCode
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.LoginReq:
    properties:
      loginName:
        type: string
      password:
        type: string
    required:
    - loginName
    - password
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.RegisterReq:
    properties:
      address:
        type: string
      confirmPassword:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender'
        enum:
        - 0
        - 1
        - 2
        - 3
      lastName:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - address
    - confirmPassword
    - dateOfBirth
    - email
    - firstName
    - password
    - username
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.ResetPasswordReq:
    properties:
      confirmPassword:
        type: string
      logoutAllDevices:
        type: boolean
      newPassword:
        minLength: 6
        type: string
    required:
    - confirmPassword
    - newPassword
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.SendForgotPasswordOtpReq:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.UpdateProfileReq:
    properties:
      address:
        type: string
      dateOfBirth:
        type: string
      firstName:
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender'
        enum:
        - 0
        - 1
        - 2
        - 3
      lastName:
        type: string
    required:
    - firstName
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.UserBodyProfileRes:
    properties:
      bodyType:
        type: string
      estimatedBodyShape:
        type: string
      fitPreference:
        type: string
      height:
        type: number
      recommendedSize:
        type: string
      skinTone:
        type: string
      stylingNotes:
        type: string
      weight:
        type: number
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.UserRes:
    properties:
      address:
        type: string
      bodyProfile:
        allOf:
        - $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserBodyProfileRes'
        description: Quota        *UserQuotaRes       `json:"quota,omitempty"`
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/smart-wardrobe-be_internal_shared_domain_constants_gender.Gender'
      id:
        type: string
      lastName:
        type: string
      roleSlug:
        type: string
      status:
        type: integer
      subscription:
        $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserSubscriptionRes'
      username:
        type: string
    type: object
  smart-wardrobe-be_internal_modules_identity_application_dto.UserSubscriptionRes:
    properties:
      aiChatDailyQuota:
        type: integer
      aiOutfitDailyQuota:
        type: integer
      expiresAt:
        type: string
      maxOutfits:
        type: integer
      maxWardrobeItems:
        type: integer
      planId:
        type: string
      planName:
        type: string
    type: object
  smart-wardrobe-be_internal_modules_subscription_application_dto.DirectPurchaseReq:
    properties:
      cancelUrl:
        type: string
      returnUrl:
        type: string
      subscriptionPlanID:
        type: string
    required:
    - subscriptionPlanID
    type: object
  smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookData:
    properties:
      accountNumber:
        type: string
      amount:
        type: integer
      code:
        type: string
      desc:
        type: string
      description:
        type: string
      orderCode:
        type: integer
      paymentLinkId:
        type: string
      reference:
        type: string
      transactionDateTime:
        type: string
    type: object
  smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookReq:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookData'
      desc:
        type: string
      signature:
        type: string
    type: object
  smart-wardrobe-be_internal_modules_subscription_application_dto.WalletTopUpReq:
    properties:
      amount:
        type: number
      cancelUrl:
        type: string
      returnUrl:
        type: string
    required:
    - amount
    type: object
  smart-wardrobe-be_internal_shared_domain_constants_gender.Gender:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Unknown
    - Male
    - Female
    - Other
  smart-wardrobe-be_internal_shared_presentation.APIResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: API docs for Smart Wardrobe.
  title: Smart Wardrobe API Document
  version: "1.0"
paths:
  /api/v1/auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Gửi mã OTP xác thực khôi phục mật khẩu qua email
      parameters:
      - description: Email nhận OTP
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.SendForgotPasswordOtpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Yêu cầu khôi phục mật khẩu
      tags:
      - Auth
  /api/v1/auth/forgot-password/confirm-otp:
    post:
      consumes:
      - application/json
      description: Xác thực mã OTP khôi phục mật khẩu và lưu token tạm thời vào cookie
      parameters:
      - description: Mã OTP và Email
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmForgotPasswordOtpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Xác thực OTP khôi phục mật khẩu
      tags:
      - Auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Đăng nhập hệ thống bằng username hoặc email và password
      parameters:
      - description: Thông tin đăng nhập
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: accessToken in data
          schema:
            allOf:
            - $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
      summary: Đăng nhập
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Đăng xuất người dùng, vô hiệu hóa token hiện tại và xóa cookie
        refresh token & access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Đăng xuất
      tags:
      - Auth
  /api/v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Sử dụng refresh token trong cookie để lấy access token mới và xoay
        vòng refresh token
      produces:
      - application/json
      responses:
        "200":
          description: accessToken in data
          schema:
            allOf:
            - $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
      summary: Xoay vòng token (Refresh Token)
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Đăng ký tài khoản mới cho người dùng và gửi OTP xác thực qua email
      parameters:
      - description: Thông tin đăng ký
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Đăng ký tài khoản
      tags:
      - Auth
  /api/v1/auth/register/confirm-otp:
    post:
      consumes:
      - application/json
      description: Xác nhận OTP gửi qua email để kích hoạt tài khoản
      parameters:
      - description: Mã OTP xác thực
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ConfirmRegisterOtpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Xác thực OTP đăng ký
      tags:
      - Auth
  /api/v1/auth/reset-password:
    post:
      consumes:
      - application/json
      description: Sử dụng token tạm thời từ cookie để tiến hành đặt mật khẩu mới
      parameters:
      - description: Mật khẩu mới và mật khẩu xác nhận
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ResetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Đặt lại mật khẩu
      tags:
      - Auth
  /api/v1/me:
    get:
      consumes:
      - application/json
      description: Lấy thông tin chi tiết tài khoản của người dùng hiện tại đang đăng
        nhập
      produces:
      - application/json
      responses:
        "200":
          description: Thông tin người dùng
          schema:
            allOf:
            - $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserRes'
              type: object
      summary: Lấy thông tin cá nhân
      tags:
      - Me
    put:
      consumes:
      - application/json
      description: Cập nhật các trường thông tin của người dùng hiện tại đang đăng
        nhập
      parameters:
      - description: Thông tin cập nhật
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UpdateProfileReq'
      produces:
      - application/json
      responses:
        "200":
          description: Thông tin người dùng sau khi cập nhật
          schema:
            allOf:
            - $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.UserRes'
              type: object
      summary: Cập nhật thông tin cá nhân
      tags:
      - Me
  /api/v1/me/change-password:
    put:
      consumes:
      - application/json
      description: Thay đổi mật khẩu cho người dùng hiện tại đang đăng nhập
      parameters:
      - description: Mật khẩu cũ và mới
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_identity_application_dto.ChangePasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Đổi mật khẩu
      tags:
      - Me
  /api/v1/subscriptions/me/daily-quota:
    get:
      consumes:
      - application/json
      description: Lấy hạn ngạch chi tiết và trạng thái sử dụng của người dùng trong
        ngày
      produces:
      - application/json
      responses:
        "200":
          description: Hạn ngạch sử dụng
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Lấy hạn ngạch sử dụng hàng ngày
      tags:
      - Subscription
  /api/v1/subscriptions/me/purchase:
    post:
      consumes:
      - application/json
      description: Khởi tạo link thanh toán VietQR qua cổng PayOS để đăng ký gói cước
        trực tiếp
      parameters:
      - description: Thông tin gói cước
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.DirectPurchaseReq'
      produces:
      - application/json
      responses:
        "200":
          description: Link thanh toán
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Đăng ký mua gói cước trực tiếp
      tags:
      - Billing
  /api/v1/subscriptions/me/toggle-auto-renew:
    patch:
      consumes:
      - application/json
      description: Bật hoặc tắt tính năng tự động gia hạn gói cước qua ví nội bộ khi
        hết hạn
      produces:
      - application/json
      responses:
        "200":
          description: Trạng thái tự động gia hạn mới
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Bật/Tắt tự động gia hạn gói cước
      tags:
      - Subscription
  /api/v1/subscriptions/me/wallet:
    get:
      consumes:
      - application/json
      description: Lấy số dư hiện có trong ví nội bộ của người dùng
      produces:
      - application/json
      responses:
        "200":
          description: Số dư ví
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Lấy số dư ví người dùng
      tags:
      - Billing
  /api/v1/subscriptions/me/wallet/statements:
    get:
      consumes:
      - application/json
      description: Lấy nhật ký biến động số dư ví nội bộ của người dùng
      produces:
      - application/json
      responses:
        "200":
          description: Danh sách lịch sử giao dịch
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Lấy lịch sử giao dịch ví nội bộ
      tags:
      - Billing
  /api/v1/subscriptions/me/wallet/topup:
    post:
      consumes:
      - application/json
      description: Khởi tạo link thanh toán VietQR qua cổng PayOS để nạp tiền vào
        ví
      parameters:
      - description: Thông tin nạp tiền
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.WalletTopUpReq'
      produces:
      - application/json
      responses:
        "200":
          description: Link thanh toán
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Tạo yêu cầu nạp tiền vào ví nội bộ
      tags:
      - Billing
  /api/v1/subscriptions/payos-webhook:
    post:
      consumes:
      - application/json
      description: Tiếp nhận và xác thực thông báo IPN từ PayOS khi người dùng thanh
        toán thành công
      parameters:
      - description: Webhook Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/smart-wardrobe-be_internal_modules_subscription_application_dto.PayOSWebhookReq'
      produces:
      - application/json
      responses:
        "200":
          description: Kết quả xử lý
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Xử lý Webhook thông báo thanh toán từ PayOS
      tags:
      - Billing
  /api/v1/subscriptions/plans:
    get:
      consumes:
      - application/json
      description: Lấy danh sách tất cả các gói đăng ký Premium hiện có
      produces:
      - application/json
      responses:
        "200":
          description: Danh sách gói cước
          schema:
            $ref: '#/definitions/smart-wardrobe-be_internal_shared_presentation.APIResponse'
      summary: Lấy danh sách các gói Premium
      tags:
      - Billing
swagger: "2.0"
